//
//  MeetingPDFExporter.swift
//  NotabilityClone
//

import AppKit
import CoreText
import PDFKit
import Foundation

enum MeetingPDFExporter {
    static func export(noteTitle: String, recording: Recording, artifact: MeetingArtifact) throws -> URL {
        let url = RecordingFileStore.shared.meetingExportURL(for: recording.id.uuidString)
        let document = buildDocument(noteTitle: noteTitle, recording: recording, artifact: artifact)
        guard document.write(to: url) else {
            throw ExportError.writeFailed
        }
        return url
    }

    static func buildDocument(noteTitle: String, recording: Recording, artifact: MeetingArtifact) -> PDFDocument {
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50
        let contentWidth = pageWidth - margin * 2

        var mediaBox = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        let data = NSMutableData()
        guard let consumer = CGDataConsumer(data: data as CFMutableData),
              let context = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
            return PDFDocument()
        }

        var y: CGFloat = pageHeight - margin
        let lineHeight: CGFloat = 16

        func beginPageIfNeeded(required: CGFloat) {
            if y - required < margin {
                context.endPDFPage()
                context.beginPDFPage(nil)
                y = pageHeight - margin
            }
        }

        func draw(_ text: String, font: NSFont, bold: Bool = false) {
            let attrs: [NSAttributedString.Key: Any] = [
                .font: bold ? NSFont.boldSystemFont(ofSize: font.pointSize) : font,
                .foregroundColor: NSColor.black
            ]
            let attrString = NSAttributedString(string: text, attributes: attrs)
            let framesetter = CTFramesetterCreateWithAttributedString(attrString)
            let suggested = CTFramesetterSuggestFrameSizeWithConstraints(
                framesetter,
                CFRange(location: 0, length: attrString.length),
                nil,
                CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                nil
            )
            beginPageIfNeeded(required: suggested.height + lineHeight)
            y -= suggested.height
            let path = CGPath(rect: CGRect(x: margin, y: y, width: contentWidth, height: suggested.height), transform: nil)
            let frame = CTFramesetterCreateFrame(framesetter, CFRange(location: 0, length: attrString.length), path, nil)
            context.textMatrix = .identity
            CTFrameDraw(frame, context)
            y -= lineHeight
        }

        context.beginPDFPage(nil)

        draw(noteTitle, font: .systemFont(ofSize: 20), bold: true)
        draw("Recording: \(recording.name)", font: .systemFont(ofSize: 12))
        draw("Date: \(recording.startedAt.formatted())", font: .systemFont(ofSize: 12))
        draw("Duration: \(formatDuration(recording.duration))", font: .systemFont(ofSize: 12))
        y -= lineHeight

        draw("Summary", font: .systemFont(ofSize: 16), bold: true)
        draw(artifact.summary.isEmpty ? "No summary available." : artifact.summary, font: .systemFont(ofSize: 11))
        y -= lineHeight

        draw("Highlights", font: .systemFont(ofSize: 16), bold: true)
        if artifact.highlights.isEmpty {
            draw("No highlights extracted.", font: .systemFont(ofSize: 11))
        } else {
            for (index, highlight) in artifact.highlights.enumerated() {
                draw("\(index + 1). [\(formatDuration(highlight.startTime))] \(highlight.title)", font: .systemFont(ofSize: 11), bold: true)
                draw(highlight.detail, font: .systemFont(ofSize: 11))
            }
        }
        y -= lineHeight

        draw("Full Transcript", font: .systemFont(ofSize: 16), bold: true)
        let sortedSegments = artifact.segments.sorted { $0.startTime < $1.startTime }
        if sortedSegments.isEmpty {
            draw(artifact.fullTranscript.isEmpty ? "No transcript available." : artifact.fullTranscript, font: .monospacedSystemFont(ofSize: 10, weight: .regular))
        } else {
            for segment in sortedSegments {
                draw("[\(formatDuration(segment.startTime))] \(segment.text)", font: .monospacedSystemFont(ofSize: 10, weight: .regular))
            }
        }

        draw("Generated by NotabilityClone — \(Date().formatted())", font: .systemFont(ofSize: 9))

        context.endPDFPage()
        context.closePDF()

        return PDFDocument(data: data as Data) ?? PDFDocument()
    }

    private static func formatDuration(_ time: TimeInterval) -> String {
        let minutes = Int(time) / 60
        let seconds = Int(time) % 60
        return String(format: "%02d:%02d", minutes, seconds)
    }

    enum ExportError: Error, LocalizedError {
        case writeFailed

        var errorDescription: String? {
            switch self {
            case .writeFailed: return "Failed to write meeting PDF."
            }
        }
    }
}
